### ISSUE TITLE
Formatter removed comma from parameter list in function definition - v54

### ISSUE THREAD

**Issue by gesslar** [jlchmura/prettier-lpc-vscode#16]
I am not entirely sure how this happened, but I have a function

`void deliver_strike_effect(object tp, object foe) {`

and the formatter changed it to

`void deliver_strike_effect(object tp object foe) {`

![image](https://github.com/jlchmura/prettier-lpc-vscode/assets/1266935/6dfb84ed-80a5-4b0e-ac18-a8d219238844)

**Comment by jlchmura** [comment]
Resolved in version 55
