### ISSUE TITLE
formatting doesn't seem to know what to do with '\0'

### ISSUE THREAD

**Issue by gesslar** [jlchmura/prettier-lpc-vscode#25]
Error message is "Unrecognized char after single quote"

Sample code:
```c
varargs int length_of_string(string some_string) {
    int i = 0 ;

    while (some_string[i] != '\0') {
        i++;
    }

    return i ;
}
```
![image](https://github.com/jlchmura/prettier-lpc-vscode/assets/1266935/5e8b94dd-2a79-4cf5-a3d8-38d89a765316)

**Comment by gesslar** [comment]
NGL, i was surprised that `'\0'` even works in Fluffy LPC. I had no idea. but it do! 😁

**Comment by jlchmura** [comment]
fixed in v60
