### ISSUE TITLE
inherit statement combining with next #define statement

### ISSUE THREAD

**Issue by gesslar** [jlchmura/prettier-lpc-vscode#27]
I don't know if this is TWO issues or not, but i'm going to include them together. Let me know and I can open a second issue if they're, in fact, two things

When I formatted this file, it took this:
```c
inherit STD_CMD;

#define MAX_FREE_GEMS 96
#define LINE "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="

string belt_slot_data(object tp);
string gem_slot_data(object tp);
string shard_slot_data(object tp);
string get_tools_data(object tp);
string get_title(object tp);
```
and converted it to this:
```c
inherit
    STD_CMD#define MAX_FREE_GEMS 96
#define LINE \
        "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=",
    belt_slot_data(object tp)
;
string gem_slot_data(object tp);
string shard_slot_data(object tp);
string get_tools_data(object tp);
string get_title(object tp);
```

1. it drew up the `#define` statement onto the same line as the inherit statement
2. it added a comma after the `#define LINE` statement and drew up the belt_slot_data() prototype as if they belonged together.

Seems kind of weird to me. 🤷🏻‍♂️

**Comment by jlchmura** [comment]
Fixed in v61
