### ISSUE TITLE
Formatter to recognize extra curly bracket

### ISSUE THREAD

**Issue by Hiryu52** [jlchmura/prettier-lpc-vscode#31]
The formatter to recognize extra curly bracket used or inadvertently used. The following check that has an extra curly bracket removes the return 0;

Example:
```
if(str != "string")
  return 0;
  {
  if(str == "string")
  {
```
Gets changed to:
```
if(str != "string")
{
  if(str == "string")
  {

```

**Comment by jlchmura** [comment]
Will be fixed in v70.  I don't plan to have to correct this weird syntax, since its technically valid.  The formatter will return:
```
  if (str != "string") return 0;
  {
    if (str == "string") {
      ...
    }
  }
```
