### ISSUE TITLE
[FluffOS ] I don't think the formatter understands use of _ as an number delimiter.

### ISSUE THREAD

**Issue by gesslar** [jlchmura/prettier-lpc-vscode#35]
It is intended to be used as a thousands delimiter, but it can be used anywhere as long as it is between integers.

Valid:
1_0
1_000
100.00_00

invalid:
1_
_1
1__0, etc

![image](https://github.com/jlchmura/prettier-lpc-vscode/assets/1266935/f091a90a-a768-4258-a1ab-05825dd1a244)

![image](https://github.com/jlchmura/prettier-lpc-vscode/assets/1266935/a0dff32c-6fb3-4572-9ba9-a596acc35f2d)

**Comment by gesslar** [comment]
Although, here, it didn't choke, it just inserted a space 😁
![image](https://github.com/jlchmura/prettier-lpc-vscode/assets/1266935/db8a3ced-cc18-45f1-b322-7c56f652035a)

**Comment by jlchmura** [comment]
@gesslar so if I wrote this code:
```int i = 1_000;```
what is the value of `i`?   `1000`?

**Comment by gesslar** [comment]
Yes
