### ISSUE TITLE
Breaks on inherit statements using __DIR__ global define

### ISSUE THREAD

**Issue by gesslar** [jlchmura/prettier-lpc-vscode#6]
In FluffOS, we have a global define of `__DIR__` which represents the directory of the current file. When inheriting, and the file we want to inherit is in the same directory, we can `inherit __DIR__ "somefile_inherit" ;`. The formatting appears to be choking on this.

For example, it stops right before `"barn_inherit"` here

```c
inherit __DIR__ "barn_inherit";

void create() {
    ::create() ;
    set("short", "`<daa>`Red Barn`<res>`") ;
```

**Comment by jlchmura** [comment]
@gesslar How do you feel about the formatting changing this into:
```
inherit (__DIR__ + "barn_inherit");
```

... I'm trying to come up with something that is still compatible with LDMud.

**Comment by cpu** [comment]
I think `inherit __DIR__ "barn_inherit";` is valid syntax on LD as-is. There's support for both implicit string constant concatenation (`"foo" "bar"` == `"foobar"`) and the `__DIR__` predefine:

```c

[14|0.000002s] return "foo" "bar";
"foobar"

[14|0.000002s] return __DIR__ "foo";
"players/paradox/secure/.lpc/foo"

```

**Comment by jlchmura** [comment]
I was thinking LD didn't like macros after `inherit`, but I just checked and @cpu is correct - this does work in LD.

**Comment by cpu** [comment]
Nice, hopefully that makes tackling this a little easier :crossed_fingers:

**Comment by jlchmura** [comment]
Included fix in v52.
