### ISSUE TITLE
Formatting a function call with ALL_CAPS argument behaviour

### ISSUE THREAD

**Issue by gesslar** [jlchmura/prettier-lpc-vscode#9]
I don't know if it's _only_ the `lower_case()` function, however, I tried multiple functions and it doesn't seem to be doing it for others, but, with this code example:
```c
#define SOME_DEFINE "some define"

void somefunc() {
    string *words ;

    words = ({ SOME_DEFINE, lower_case(SOME_DEFINE), upper_case(SOME_DEFINE) }) ;
}
```
when I format document, it puts `lower_case` on its own and `(SOME_DEFINE)` on its own in this array.
Result:
```c
#define SOME_DEFINE "some define"

void somefunc() {
    string *words;

    words = ({SOME_DEFINE, lower_case, (SOME_DEFINE), upper_case(SOME_DEFINE)});
}
```

**Comment by jlchmura** [comment]
This will be fixed in v49.  Thanks for submitting the issue!
